export const projects = 
[
  {
    id: 'shubham-jewellers',
    title: 'Shubham Jewellers',
    role: 'Freelance Developer',
    year: '2025',
    description: 'Real business CRM with automated PDF invoicing, competitor price scraping, and a 3D product showcase.',
    longDescription: 'Production CRM built for a real jewellery business (78+ commits). Centralized inventory management, customer relationships, and automated PDF invoice generation. Features a 3D product showcase built with Three.js + GSAP.',
    architecture: 'Client-server architecture using Next.js for optimized routing and SSR, connected to MongoDB. Puppeteer runs server-side for automated document generation.',
    implementation: 'Integrated Three.js for interactive 3D product rendering on the frontend. Puppeteer handles PDF invoice generation on the server. BeautifulSoup (Python) scrapes competitor pricing data automatically.',
    stack: ['Next.js', 'TypeScript', 'MongoDB', 'Puppeteer', 'Three.js', 'GSAP', 'BeautifulSoup', 'Python', 'Vercel'],
    url: 'https://shubham-jewellers.vercel.app',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=2070',
  },
  {
    id: 'pickmypet',
    title: 'PickMyPet',
    role: 'Full Stack Developer',
    year: '2025',
    description: 'Pet adoption platform with real-time chat, JWT auth, Redis caching, and a full admin panel.',
    longDescription: 'Three-tier system (frontend, backend, admin panel) bridging pet shelters and adopters. Real-time messaging via Socket.IO, secure JWT + RBAC auth, Redis caching, and Cloudinary for image uploads. Ongoing — new features added regularly.',
    architecture: 'Distributed across 3 separate repos. Event-driven, real-time architecture powered by Node.js, Socket.IO, Redis pub/sub, and Kafka for async pipelines.',
    implementation: 'Built dynamic UIs with React and Redux Toolkit. JWT + RBAC for secure access control. Socket.IO for real-time chat with Redis caching reducing latency. Cloudinary for high-performance image handling.',
    stack: ['Node.js', 'TypeScript', 'React.js', 'Redux Toolkit', 'Socket.IO', 'Redis', 'MongoDB', 'JWT', 'Kafka', 'Cloudinary', 'Vite'],
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=2070',
  },
  {
    id: 'drafted-jobs',
    title: 'drafted.jobs',
    role: 'Solo Engineer',
    year: '2026',
    description: 'AI-powered job hunting desktop app that autonomously scouts boards, scores roles against your resume, and delivers precision-matched leads.',
    longDescription: 'Industrial-grade autonomous job scout. Scrapes LinkedIn, Indeed, and more simultaneously using Playwright + Chrome profile connection. NVIDIA NIM LLMs score each role mathematically against your resume. Results land in a Kanban dashboard. Ships as a native desktop app via Electron.',
    architecture: 'Next.js 16 + Electron desktop shell communicating with a FastAPI Python backend. A "Scout Engine" powered by Playwright streams live data to the UI via Server-Sent Events (SSE).',
    implementation: 'Playwright connects to an existing Chrome profile to bypass anti-bot measures. NVIDIA NIM API scores job-resume match mathematically. Packaged and distributed as a native desktop app via Electron Builder.',
    stack: ['Next.js 16', 'Electron', 'TypeScript', 'FastAPI', 'Python', 'Playwright', 'NVIDIA NIM', 'PostgreSQL', 'Redis', 'Tailwind CSS v4'],
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=2070',
  },
  {
    id: 'vet-care-ai',
    title: 'Vet Care AI',
    role: 'Full Stack Lead',
    year: '2026',
    description: 'AI-powered veterinary practice management SaaS for UK clinics.',
    longDescription: 'Built the entire product solo end-to-end. Features RAG-based AI assistant using Gemini, LangChain, and ChromaDB for instant medical triage and pet parent support.',
    stack: ['FastAPI', 'Next.js', 'PostgreSQL', 'Gemini', 'LangChain', 'ChromaDB', 'Redis'],
    architecture: 'Microservices architecture with FastAPI backend and Next.js frontend, utilizing ChromaDB for vector storage and Gemini for LLM processing.',
    implementation: 'Integrated WhatsApp Business API for automated bookings, resulting in 40-60% fewer no-shows. Implemented a custom RAG pipeline for domain-specific veterinary knowledge.',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?q=80&w=2070',
  },
];
